### ISSUE TITLE
Publish to a Maven repository

### ISSUE THREAD

**Issue by bowbahdoe** [AharonSambol/PrettyPrintTreeJava#2]
The simplest would be jitpack, would require adding some maven build stuff to the repo though

**Comment by AharonSambol** [comment]
After hours of trying... I give up... sorry

**Comment by bowbahdoe** [comment]
If you want I can help you out with this on the weekend. I know its frustrating

**Comment by bowbahdoe** [comment]
Okay I did the stuff to move the code to maven in #3 . If you accept that PR then you can publish by pointing https://jitpack.io/ at your repo.

**Comment by AharonSambol** [comment]
OK I accepted the PR, not sure what you mean about pointing jitpack at the repo? All I get when going to that link is instructions on how to get a published project into the build... I don't think that's what I want...
Sorry for all the trouble 😅

**Comment by bowbahdoe** [comment]
Okay so basically those instructions are all you need. The first time someone tries to use them jitpack will trigger a build.

https://jitpack.io/com/github/AharonSambol/PrettyPrintTreeJava/main-0b6c76a0e2-1/build.log

So now by including the jitpack repository I can use your code like this

```xml
	<dependency>
	    <groupId>com.github.AharonSambol</groupId>
	    <artifactId>PrettyPrintTreeJava</artifactId>
	    <version>main-SNAPSHOT</version>
	</dependency>
```

(usually i would replace main-SNAPSHOT with a particular hash or if you make a tag you can use that as the version)

**Comment by bowbahdoe** [comment]
Publishing to "Maven Central" is a bit more work and is worth it if you want to be truly "published", but with jitpack at least folks can use the code and at least for now the repository seems reliable

**Comment by AharonSambol** [comment]
Oh cool! Thanks you!
