### ISSUE TITLE
Can't use immputable List.of() in getChildren() method because app throws UnsupportedOperationException

### ISSUE THREAD

**Issue by olekstomek** [AharonSambol/PrettyPrintTreeJava#7]
> Exception in thread "main" java.lang.UnsupportedOperationException
> 	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:72)
> 	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.removeAll(ImmutableCollections.java:80)
> 	at ajs.printutils.PrettyPrintTree.treeToStr(PrettyPrintTree.java:89)
> 	at ajs.printutils.PrettyPrintTree.toStr(PrettyPrintTree.java:50)
> 	at ajs.printutils.PrettyPrintTree.toStr(PrettyPrintTree.java:47)
> 	at ajs.printutils.PrettyPrintTree.display(PrettyPrintTree.java:46) 

You can check it here: https://youtu.be/GatEI4l7ypw?t=668 (PL language)

**Comment by AharonSambol** [comment]
I fixed the issue of the immutable lists, however using List.of still won't work because it throws an error if passed null (@ NotNull) which is what happens in the bottom nodes. So you'll still be better off using:
```
return new ArrayList<>(){{
            add(left);
            add(right);
        }};
```
Hope this helps!

**Comment by AharonSambol** [comment]
I've added a warning in the readme as well

**Comment by olekstomek** [comment]
Thanks for your interest in the topic. 👍
